name: 'test_snowflake'
version: '1.0.0'

profile: 'test_snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  test_snowflake:
    example:
      +materialized: view