name: 'test_snowflake'
version: '1.0.0'

profile: 'test_snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  test_snowflake:
    01_bronze_layer:
      +materialized: ephemeral # 임시테이블
    02_silver_layer:
      +materialized: table # 테이블
      +schema: SILVER_DATA