name: 'dbt_snowflake_name'
version: '1.0.1'

profile: 'dbt_snowflake_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_snowflake:
    01_bronze_layer:

    02_silver_layer:

    03_gold_layer: