WITH LATEST_DATA AS (
    SELECT DISTINCT *
    FROM {{ ref('match_player_details') }}
    WHERE CREATED_AT = (
            SELECT MAX(CREATED_AT)
            FROM {{ ref('match_player_details') }}
    )
)
SELECT 
    PLACEMENT,
    CAST(AVG(TOTAL_DAMAGE_TO_PLAYERS)as int) AS AVG_TOTAL_DAMAGE_TO_PLAYERS,
    ROUND(AVG(LEVEL), 2) AS AVG_LEVEL,
    ROUND(AVG(LAST_ROUND), 2) AS AVG_LAST_ROUND
FROM LATEST_DATA
GROUP BY PLACEMENT
ORDER BY PLACEMENT